[package]
authors = ["kizkoh"]
name = "webapp"
version = "0.1.0"

[dependencies]
chrono = "0.2.25"
hyper = "0.9.13"
lazy_static = "0.2.2"
mysql = "7.1.2"
nickel = "0.9.0"
serde = "0.8.19"
serde_derive = "0.8.19"
serde_json = "0.8.3"
uuid = "0.3.1"
